name: main

on:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dart
        uses: dart-lang/setup-dart@v1

      - name: Install HomeBrew
        working-directory: ${{ github.workspace }}
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install lcov
        working-directory: ${{ github.workspace }}
        run: brew install lcov

      # - name: Generate coverage badge
      #   working-directory: ${{ github.workspace }}
      #   run: dart run change-number.dart

      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     message: "change number"

      # - name: Checkout code
      #   uses: actions/checkout@v2
      #   with:
      #     ref: develop

      # - name: Pull request from main to develop
      #   run: git pull origin main
